In [ ]:
from cluster_characteristics import *

In [2]:
from sklearn.datasets import load_digits
digits = load_digits()
pd_df=pd.DataFrame(digits.data)
pd_df['target'] = digits.target
pd_df

,0,1,2,3,4,5,6,7,8,9,...,55,56,57,58,59,60,61,62,63,target
0,0.0,0.0,5.0,13.0,9.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,13.0,10.0,0.0,0.0,0.0,0
1,0.0,0.0,0.0,12.0,13.0,5.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,11.0,16.0,10.0,0.0,0.0,1
2,0.0,0.0,0.0,4.0,15.0,12.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,3.0,11.0,16.0,9.0,0.0,2
3,0.0,0.0,7.0,15.0,13.0,1.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,7.0,13.0,13.0,9.0,0.0,0.0,3
4,0.0,0.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,2.0,16.0,4.0,0.0,0.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1792,0.0,0.0,4.0,10.0,13.0,6.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,2.0,14.0,15.0,9.0,0.0,0.0,9
1793,0.0,0.0,6.0,16.0,13.0,11.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,6.0,16.0,14.0,6.0,0.0,0.0,0
1794,0.0,0.0,1.0,11.0,15.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,2.0,9.0,13.0,6.0,0.0,0.0,8
1795,0.0,0.0,2.0,10.0,7.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,5.0,12.0,16.0,12.0,0.0,0.0,9
1796,0.0,0.0,10.0,14.0,8.0,1.0,0.0,0.0,0.0,2.0,...,0.0,0.0,1.0,8.0,12.0,14.0,12.0,1.0,0.0,8

In [3]:
CC=ClusterCharacteristics(pd_df, "target")

In [4]:
public_method_names = [f for f in dir(ClusterCharacteristics) if not f.startswith('_')]
public_method_names

['PCA_2D_graph',
 'PCA_3D_graph',
 'clusters_info',
 'confusion_hyperphere_around_specific_point_for_two_clusters',
 'confusion_hypersphere_for_linspace_radius_each_element',
 'confusion_hypersphere_matrix',
 'data_PCA',
 'data_every_distance_between_elements_of_two_clusters',
 'data_intercentroid_distance',
 'data_intercentroid_distance_matrix',
 'data_interelement_distance',
 'data_interelement_distance_maximum_for_different_clusters',
 'data_interelement_distance_minimum_for_different_clusters',
 'data_radius_selector_specific_cluster',
 'general_info',
 'graph_boxplots_distances_to_centroid',
 'graph_umap_reduce_results',
 'projection_2D',
 'scatter_matrix_T',
 'scatter_matrix_WG',
 'scatter_matrix_between_group_BG',
 'scatter_matrix_specific_cluster_WGk',
 'score_between_group_dispersion',
 'score_index_PBM',
 'score_index_SD',
 'score_index_S_Dbw',
 'score_index_ball_hall',
 'score_index_banfeld_Raftery',
 'score_index_c',
 'score_index_c_for_each_cluster',
 'score_index_calinski_harabasz',
 'score_index_davies_bouldin',
 'score_index_davies_bouldin_for_each_cluster',
 'score_index_det_ratio',
 'score_index_dunn',
 'score_index_generalized_dunn',
 'score_index_generalized_dunn_matrix',
 'score_index_info',
 'score_index_log_ss_ratio',
 'score_index_ratkowsky_lance',
 'score_index_ray_turi',
 'score_index_rules',
 'score_index_silhouette',
 'score_index_silhouette_for_every_cluster',
 'score_index_trace_WiB',
 'score_index_wemmert_gancarski',
 'score_index_xie_beni',
 'score_mean_quadratic_error',
 'score_pooled_within_cluster_dispersion',
 'score_totalsumsquare',
 'score_within_cluster_dispersion']

In [5]:
CC.confusion_hypersphere_matrix(radius=20,counting_type='including',proportion=True)

,C:0,C:1,C:2,C:3,C:4,C:5,C:6,C:7,C:8,C:9
H:0,0.595506,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
H:1,0.000000,0.021978,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
H:2,0.000000,0.000000,0.079096,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
H:3,0.000000,0.000000,0.000000,0.191257,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
H:4,0.000000,0.000000,0.000000,0.000000,0.138122,0.000000,0.000000,0.000000,0.00000,0.000000
H:5,0.000000,0.000000,0.000000,0.000000,0.000000,0.038462,0.000000,0.000000,0.00000,0.000000
H:6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.353591,0.000000,0.00000,0.000000
H:7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.122905,0.00000,0.000000
H:8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.04023,0.000000
H:9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.122222